volumes:
  db-store:
  psysh-store:

configs:
  db-config:
    file: ./.docker/docker/mysql/my.cnf

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - type: bind
        source: ./backend
        target: /workspace
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-root}

  web:
    build:
      context: .
      dockerfile: ./.docker/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-8800}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./backend
        target: /workspace

  db:
    build:
      context: .
      dockerfile: ./.docker/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PUBLISHED_PORT:-3307}
        protocol: tcp
        mode: host
    configs:
      - source: db-config
        target: /etc/my.cnf
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}

  mailpit:
    image: axllent/mailpit
    ports:
      - target: 8025
        published: ${MAILPIT_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host

  phpmyadmin:
    container_name: laravel-phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - target: 80
        published: ${PHPMYADMIN_PORT:-8888}
        protocol: tcp
        mode: host
    depends_on:
      - db

  vue-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: ${FRONTEND_PUBLISHED_PORT:-8181}
        protocol: tcp
        mode: host
    container_name: vue-ui
    # volumes:
    #    - ./frontend:/usr/src/app/frontend
    #    - /usr/src/app/frontend/node_modules
