name: deploy-update-server

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install sshpass
        run: sudo apt-get install -y sshpass


      - name: Deploy to Server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            # Commands to create agent and add SSH key
            eval "$(ssh-agent -s)"
            ssh-add - <<<"${{ secrets.Gitkey }}"
            
            # Pull latest changes and run make install
            cd /var/www/html/docker-laravel
            git pull origin main
            make install
          '